Training_Settings:
  lr: 0.01
  optim: "sgd"
  epochs: 10
  batch_size: 8
  test_batch: 32
  save_epoch: 20
  seed: 0
  workers: 8
  seq_len: 12

Model_Settings:
  arch: "resnet50"
  drop: 0.2
  low_dim: 512
  part: 3
  margin: 0.3
  num_pos: 2

Data_Processing:
  img_w: 144
  img_h: 288